name: Verify code compiles
on: [push]

jobs:
  compile-check:
    timeout-minutes: 7
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install NPM packages
        run: npm install

      - name: Create bundle
        run: npm run build